on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_FIREFOX_EXT_ID: ${{ secrets.FIREFOX_EXT_ID }}

      - name: Install dependencies and build extension
        run: pnpm i && pnpm build --zip && pnpm build --target=firefox-mv2 --zip

      - name: Publish extension
        uses: PlasmoHQ/bpp@v3.1.0
        with:
          keys: ${{ secrets.BPP_KEYS }}
          firefox-file: build/firefox-mv2-prod.zip
          chrome-file: build/chrome-mv3-prod.zip
